// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQF5hpPOL5xIKcO6na_ajYbXaELFHZtmE',
    appId: '1:431443052590:web:72fd71536f249bfc45b7bf',
    messagingSenderId: '431443052590',
    projectId: 'screenproject-100d7',
    authDomain: 'screenproject-100d7.firebaseapp.com',
    databaseURL: 'https://screenproject-100d7-default-rtdb.firebaseio.com',
    storageBucket: 'screenproject-100d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoymgV30dkVhVn2P3R_xtUO_f9eosH0N0',
    appId: '1:431443052590:android:a6af1977689b37cb45b7bf',
    messagingSenderId: '431443052590',
    projectId: 'screenproject-100d7',
    databaseURL: 'https://screenproject-100d7-default-rtdb.firebaseio.com',
    storageBucket: 'screenproject-100d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7dfFtU60yDASmmChq2gecSL6Xy9fMc8',
    appId: '1:431443052590:ios:1cef30ffa768281945b7bf',
    messagingSenderId: '431443052590',
    projectId: 'screenproject-100d7',
    databaseURL: 'https://screenproject-100d7-default-rtdb.firebaseio.com',
    storageBucket: 'screenproject-100d7.appspot.com',
    androidClientId: '431443052590-72m08j5iuj1sbbt2k73di33as619vfdu.apps.googleusercontent.com',
    iosClientId: '431443052590-0b5vg9556450n2g33lepptem0sjpmbvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.screenProject',
  );
}
